##HTML Y FRONTEND

##HTML : HIPERTEXT MARKUP LANGUAGE // LA ESTRUCTURA DE LA PAGINA WEB.
##CSS: CASCADING STYLE SHEET // LA APARIENCIA DE LA PAGINA WEB.
##JS: JAVASCRIPT // LA INTERACTIVIDAD O FUNCIONES DE LA PAGINA WEB.

##Primer proyecto: CREAR UN CURRICULUM VITAE EN HTML CON LAS HERRAMIENTAS QUE SE ESTAN APRENDIENDO.